// <auto-generated />
namespace DinhVoSongThu_2011068739.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KhoitaodulieuchobangCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoitaodulieuchobangCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202303040306383_Khoi tao du lieu cho bang Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
